name: Deploy storybook to GH Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build and deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
      - run: npm ci
      - run: npm run build-storybook
        with:
          publish_dir: ./storybook-static
